/*
Tên file: data_quality_report.sql
Mô tả: Báo cáo chất lượng dữ liệu của các bảng nguồn sử dụng bởi các mô hình
Tác giả: Nguyễn Ngọc Bình
Ngày tạo: 2025-05-12
Phiên bản: 1.0

Báo cáo này cung cấp thông tin về chất lượng dữ liệu của các bảng nguồn,
vấn đề chất lượng dữ liệu, tình trạng cập nhật và tác động đến các mô hình.
*/

-- 1. Báo cáo tổng quan về chất lượng dữ liệu
SELECT 
    'BÁO CÁO CHẤT LƯỢNG DỮ LIỆU - ' + CONVERT(VARCHAR, GETDATE(), 103) AS REPORT_TITLE;

-- 1.1. Thống kê tổng quan về chất lượng dữ liệu
SELECT 
    'THỐNG KÊ TỔNG QUAN CHẤT LƯỢNG DỮ LIỆU' AS SECTION_TITLE;

SELECT
    COUNT(DISTINCT st.SOURCE_TABLE_ID) AS TONG_SO_BANG,
    SUM(CASE WHEN st.IS_ACTIVE = 1 THEN 1 ELSE 0 END) AS SO_BANG_DANG_HOAT_DONG,
    SUM(CASE WHEN st.DATA_QUALITY_SCORE >= 8 THEN 1 ELSE 0 END) AS SO_BANG_CHAT_LUONG_TOT,
    SUM(CASE WHEN st.DATA_QUALITY_SCORE BETWEEN 5 AND 7 THEN 1 ELSE 0 END) AS SO_BANG_CHAT_LUONG_TRUNG_BINH,
    SUM(CASE WHEN st.DATA_QUALITY_SCORE < 5 AND st.DATA_QUALITY_SCORE IS NOT NULL THEN 1 ELSE 0 END) AS SO_BANG_CHAT_LUONG_THAP,
    SUM(CASE WHEN st.DATA_QUALITY_SCORE IS NULL THEN 1 ELSE 0 END) AS SO_BANG_CHUA_DANH_GIA,
    (
        SELECT COUNT(DISTINCT dq.LOG_ID)
        FROM MODEL_REGISTRY.dbo.MODEL_DATA_QUALITY_LOG dq
        WHERE dq.REMEDIATION_STATUS IN ('OPEN', 'IN_PROGRESS')
    ) AS TONG_SO_VAN_DE_DANG_MO,
    (
        SELECT COUNT(DISTINCT dq.LOG_ID)
        FROM MODEL_REGISTRY.dbo.MODEL_DATA_QUALITY_LOG dq
        WHERE dq.REMEDIATION_STATUS IN ('OPEN', 'IN_PROGRESS')
        AND dq.SEVERITY = 'CRITICAL'
    ) AS SO_VAN_DE_NGHIEM_TRONG,
    (
        SELECT COUNT(DISTINCT SOURCE_TABLE_ID)
        FROM MODEL_REGISTRY.dbo.MODEL_SOURCE_REFRESH_LOG
        WHERE REFRESH_STATUS = 'COMPLETED'
        AND PROCESS_DATE >= DATEADD(DAY, -7, GETDATE())
    ) AS SO_BANG_CAP_NHAT_TRONG_7_NGAY
FROM MODEL_REGISTRY.dbo.MODEL_SOURCE_TABLES st;

-- 1.2. Thống kê chất lượng dữ liệu theo loại bảng
SELECT 
    'THỐNG KÊ CHẤT LƯỢNG DỮ LIỆU THEO LOẠI BẢNG' AS SECTION_TITLE;

SELECT
    st.TABLE_TYPE AS LOAI_BANG,
    COUNT(DISTINCT st.SOURCE_TABLE_ID) AS SO_LUONG_BANG,
    AVG(CAST(st.DATA_QUALITY_SCORE AS FLOAT)) AS DIEM_CHAT_LUONG_TRUNG_BINH,
    MIN(st.DATA_QUALITY_SCORE) AS DIEM_CHAT_LUONG_THAP_NHAT,
    MAX(st.DATA_QUALITY_SCORE) AS DIEM_CHAT_LUONG_CAO_NHAT,
    SUM(CASE WHEN st.DATA_QUALITY_SCORE >= 8 THEN 1 ELSE 0 END) AS SO_BANG_CHAT_LUONG_TOT,
    SUM(CASE WHEN st.DATA_QUALITY_SCORE < 5 AND st.DATA_QUALITY_SCORE IS NOT NULL THEN 1 ELSE 0 END) AS SO_BANG_CHAT_LUONG_THAP,
    (
        SELECT COUNT(DISTINCT dq.LOG_ID)
        FROM MODEL_REGISTRY.dbo.MODEL_DATA_QUALITY_LOG dq
        WHERE dq.SOURCE_TABLE_ID = st.SOURCE_TABLE_ID
        AND dq.REMEDIATION_STATUS IN ('OPEN', 'IN_PROGRESS')
    ) AS SO_VAN_DE_DANG_MO
FROM MODEL_REGISTRY.dbo.MODEL_SOURCE_TABLES st
GROUP BY st.TABLE_TYPE
ORDER BY SO_LUONG_BANG DESC;

-- 2. Báo cáo chi tiết về bảng dữ liệu
SELECT 
    'CHI TIẾT CHẤT LƯỢNG TỪNG BẢNG DỮ LIỆU' AS SECTION_TITLE;

-- 2.1. Danh sách các bảng dữ liệu và chất lượng
SELECT
    st.SOURCE_TABLE_ID,
    st.SOURCE_DATABASE + '.' + st.SOURCE_SCHEMA + '.' + st.SOURCE_TABLE_NAME AS TEN_BANG_DAY_DU,
    st.TABLE_TYPE AS LOAI_BANG,
    st.DATA_OWNER AS CHU_SO_HUU_DU_LIEU,
    st.UPDATE_FREQUENCY AS TAN_SUAT_CAP_NHAT,
    st.DATA_LATENCY AS DO_TRE_DU_LIEU,
    st.DATA_QUALITY_SCORE AS DIEM_CHAT_LUONG,
    (
        SELECT COUNT(DISTINCT tu.MODEL_ID)
        FROM MODEL_REGISTRY.dbo.MODEL_TABLE_USAGE tu
        JOIN MODEL_REGISTRY.dbo.MODEL_REGISTRY mr ON tu.MODEL_ID = mr.MODEL_ID
        WHERE tu.SOURCE_TABLE_ID = st.SOURCE_TABLE_ID
        AND tu.IS_ACTIVE = 1
        AND mr.IS_ACTIVE = 1
        AND GETDATE() BETWEEN mr.EFF_DATE AND mr.EXP_DATE
    ) AS SO_LUONG_MO_HINH_SU_DUNG,
    (
        SELECT MAX(PROCESS_DATE)
        FROM MODEL_REGISTRY.dbo.MODEL_SOURCE_REFRESH_LOG srl
        WHERE srl.SOURCE_TABLE_ID = st.SOURCE_TABLE_ID
        AND srl.REFRESH_STATUS = 'COMPLETED'
    ) AS NGAY_CAP_NHAT_CUOI,
    (
        SELECT COUNT(*)
        FROM MODEL_REGISTRY.dbo.MODEL_DATA_QUALITY_LOG dq
        WHERE dq.SOURCE_TABLE_ID = st.SOURCE_TABLE_ID
        AND dq.REMEDIATION_STATUS IN ('OPEN', 'IN_PROGRESS')
    ) AS SO_VAN_DE_DANG_MO,
    (
        SELECT COUNT(*)
        FROM MODEL_REGISTRY.dbo.MODEL_DATA_QUALITY_LOG dq
        WHERE dq.SOURCE_TABLE_ID = st.SOURCE_TABLE_ID
        AND dq.REMEDIATION_STATUS IN ('OPEN', 'IN_PROGRESS')
        AND dq.SEVERITY = 'CRITICAL'
    ) AS SO_VAN_DE_NGHIEM_TRONG,
    CASE 
        WHEN st.DATA_QUALITY_SCORE >= 8 THEN 'Tốt'
        WHEN st.DATA_QUALITY_SCORE BETWEEN 5 AND 7 THEN 'Trung bình'
        WHEN st.DATA_QUALITY_SCORE < 5 AND st.DATA_QUALITY_SCORE IS NOT NULL THEN 'Thấp'
        ELSE 'Chưa đánh giá'
    END AS DANH_GIA_CHAT_LUONG
FROM MODEL_REGISTRY.dbo.MODEL_SOURCE_TABLES st
ORDER BY 
    SO_LUONG_MO_HINH_SU_DUNG DESC,
    DIEM_CHAT_LUONG ASC;

-- 2.2. Cập nhật dữ liệu gần đây
SELECT 
    'TRẠNG THÁI CẬP NHẬT DỮ LIỆU GẦN ĐÂY' AS SECTION_TITLE;

WITH LastRefresh AS (
    SELECT 
        srl.SOURCE_TABLE_ID,
        MAX(srl.PROCESS_DATE) AS LAST_REFRESH_DATE,
        MAX(srl.REFRESH_END_TIME) AS LAST_REFRESH_TIME,
        DATEDIFF(DAY, MAX(srl.PROCESS_DATE), GETDATE()) AS DAYS_SINCE_REFRESH
    FROM MODEL_REGISTRY.dbo.MODEL_SOURCE_REFRESH_LOG srl
    WHERE srl.REFRESH_STATUS = 'COMPLETED'
    GROUP BY srl.SOURCE_TABLE_ID
)
SELECT
    st.SOURCE_DATABASE + '.' + st.SOURCE_SCHEMA + '.' + st.SOURCE_TABLE_NAME AS TEN_BANG_DAY_DU,
    st.TABLE_TYPE AS LOAI_BANG,
    st.UPDATE_FREQUENCY AS TAN_SUAT_CAP_NHAT,
    CONVERT(VARCHAR, lr.LAST_REFRESH_DATE, 103) AS NGAY_CAP_NHAT_CUOI,
    lr.DAYS_SINCE_REFRESH AS SO_NGAY_TU_CAP_NHAT_CUOI,
    (
        SELECT TOP 1 srl.RECORDS_PROCESSED
        FROM MODEL_REGISTRY.dbo.MODEL_SOURCE_REFRESH_LOG srl
        WHERE srl.SOURCE_TABLE_ID = st.SOURCE_TABLE_ID
        AND srl.REFRESH_STATUS = 'COMPLETED'
        ORDER BY srl.PROCESS_DATE DESC, srl.REFRESH_END_TIME DESC
    ) AS SO_BAN_GHI_XU_LY,
    (
        SELECT COUNT(DISTINCT tu.MODEL_ID)
        FROM MODEL_REGISTRY.dbo.MODEL_TABLE_USAGE tu
        JOIN MODEL_REGISTRY.dbo.MODEL_REGISTRY mr ON tu.MODEL_ID = mr.MODEL_ID
        WHERE tu.SOURCE_TABLE_ID = st.SOURCE_TABLE_ID
        AND tu.IS_ACTIVE = 1
        AND mr.IS_ACTIVE = 1
        AND GETDATE() BETWEEN mr.EFF_DATE AND mr.EXP_DATE
    ) AS SO_LUONG_MO_HINH_SU_DUNG,
    CASE 
        WHEN st.UPDATE_FREQUENCY = 'DAILY' AND lr.DAYS_SINCE_REFRESH > 1 THEN 'Trễ'
        WHEN st.UPDATE_FREQUENCY = 'WEEKLY' AND lr.DAYS_SINCE_REFRESH > 7 THEN 'Trễ'
        WHEN st.UPDATE_FREQUENCY = 'MONTHLY' AND lr.DAYS_SINCE_REFRESH > 31 THEN 'Trễ'
        WHEN st.UPDATE_FREQUENCY = 'QUARTERLY' AND lr.DAYS_SINCE_REFRESH > 92 THEN 'Trễ'
        WHEN lr.DAYS_SINCE_REFRESH > 31 THEN 'Kiểm tra'
        ELSE 'Đúng hạn'
    END AS TRANG_THAI_CAP_NHAT
FROM MODEL_REGISTRY.dbo.MODEL_SOURCE_TABLES st
LEFT JOIN LastRefresh lr ON st.SOURCE_TABLE_ID = lr.SOURCE_TABLE_ID
WHERE st.IS_ACTIVE = 1
ORDER BY 
    CASE 
        WHEN st.UPDATE_FREQUENCY = 'DAILY' AND lr.DAYS_SINCE_REFRESH > 1 THEN 1
        WHEN st.UPDATE_FREQUENCY = 'WEEKLY' AND lr.DAYS_SINCE_REFRESH > 7 THEN 2
        WHEN st.UPDATE_FREQUENCY = 'MONTHLY' AND lr.DAYS_SINCE_REFRESH > 31 THEN 3
        WHEN st.UPDATE_FREQUENCY = 'QUARTERLY' AND lr.DAYS_SINCE_REFRESH > 92 THEN 4
        WHEN lr.DAYS_SINCE_REFRESH > 31 THEN 5
        ELSE 6
    END,
    SO_LUONG_MO_HINH_SU_DUNG DESC;

-- 3. Báo cáo chi tiết về vấn đề chất lượng dữ liệu
SELECT 
    'CÁC VẤN ĐỀ CHẤT LƯỢNG DỮ LIỆU ĐANG MỞ' AS SECTION_TITLE;

-- 3.1. Vấn đề chất lượng dữ liệu nghiêm trọng
SELECT 
    'VẤN ĐỀ CHẤT LƯỢNG DỮ LIỆU NGHIÊM TRỌNG' AS SECTION_TITLE;

SELECT
    dq.LOG_ID,
    st.SOURCE_DATABASE + '.' + st.SOURCE_SCHEMA + '.' + st.SOURCE_TABLE_NAME AS TEN_BANG,
    ISNULL(cd.COLUMN_NAME, 'N/A') AS TEN_COT,
    CONVERT(VARCHAR, dq.PROCESS_DATE, 103) AS NGAY_PHAT_HIEN,
    dq.ISSUE_TYPE AS LOAI_VAN_DE,
    dq.ISSUE_DESCRIPTION AS MO_TA_VAN_DE,
    dq.RECORDS_AFFECTED AS SO_BAN_GHI_ANH_HUONG,
    dq.PERCENTAGE_AFFECTED AS PHAN_TRAM_ANH_HUONG,
    dq.REMEDIATION_STATUS AS TRANG_THAI_XU_LY,
    dq.REMEDIATION_ACTION AS HANH_DONG_XU_LY,
    dq.IMPACT_DESCRIPTION AS MO_TA_TAC_DONG,
    DATEDIFF(DAY, dq.PROCESS_DATE, GETDATE()) AS SO_NGAY_MO,
    (
        SELECT COUNT(DISTINCT tu.MODEL_ID)
        FROM MODEL_REGISTRY.dbo.MODEL_TABLE_USAGE tu
        JOIN MODEL_REGISTRY.dbo.MODEL_REGISTRY mr ON tu.MODEL_ID = mr.MODEL_ID
        WHERE tu.SOURCE_TABLE_ID = st.SOURCE_TABLE_ID
        AND tu.IS_ACTIVE = 1
        AND mr.IS_ACTIVE = 1
        AND GETDATE() BETWEEN mr.EFF_DATE AND mr.EXP_DATE
    ) AS SO_LUONG_MO_HINH_ANH_HUONG
FROM MODEL_REGISTRY.dbo.MODEL_DATA_QUALITY_LOG dq
JOIN MODEL_REGISTRY.dbo.MODEL_SOURCE_TABLES st ON dq.SOURCE_TABLE_ID = st.SOURCE_TABLE_ID
LEFT JOIN MODEL_REGISTRY.dbo.MODEL_COLUMN_DETAILS cd ON dq.COLUMN_ID = cd.COLUMN_ID
WHERE dq.REMEDIATION_STATUS IN ('OPEN', 'IN_PROGRESS')
AND dq.SEVERITY = 'CRITICAL'
ORDER BY dq.PROCESS_DATE;

-- 3.2. Tất cả các vấn đề chất lượng dữ liệu đang mở
SELECT 
    'TẤT CẢ CÁC VẤN ĐỀ CHẤT LƯỢNG DỮ LIỆU ĐANG MỞ' AS SECTION_TITLE;

SELECT
    dq.LOG_ID,
    st.SOURCE_DATABASE + '.' + st.SOURCE_SCHEMA + '.' + st.SOURCE_TABLE_NAME AS TEN_BANG,
    ISNULL(cd.COLUMN_NAME, 'N/A') AS TEN_COT,
    CONVERT(VARCHAR, dq.PROCESS_DATE, 103) AS NGAY_PHAT_HIEN,
    dq.SEVERITY AS MUC_DO_NGHIEM_TRONG,
    dq.ISSUE_TYPE AS LOAI_VAN_DE,
    dq.ISSUE_DESCRIPTION AS MO_TA_VAN_DE,
    dq.REMEDIATION_STATUS AS TRANG_THAI_XU_LY,
    DATEDIFF(DAY, dq.PROCESS_DATE, GETDATE()) AS SO_NGAY_MO
FROM MODEL_REGISTRY.dbo.MODEL_DATA_QUALITY_LOG dq
JOIN MODEL_REGISTRY.dbo.MODEL_SOURCE_TABLES st ON dq.SOURCE_TABLE_ID = st.SOURCE_TABLE_ID
LEFT JOIN MODEL_REGISTRY.dbo.MODEL_COLUMN_DETAILS cd ON dq.COLUMN_ID = cd.COLUMN_ID
WHERE dq.REMEDIATION_STATUS IN ('OPEN', 'IN_PROGRESS')
ORDER BY 
    CASE dq.SEVERITY
        WHEN 'CRITICAL' THEN 1
        WHEN 'HIGH' THEN 2
        WHEN 'MEDIUM' THEN 3
        WHEN 'LOW' THEN 4
        ELSE 5
    END,
    dq.PROCESS_DATE;

-- 3.3. Thống kê vấn đề theo loại
SELECT 
    'THỐNG KÊ VẤN ĐỀ THEO LOẠI' AS SECTION_TITLE;

SELECT
    dq.ISSUE_TYPE AS LOAI_VAN_DE,
    COUNT(*) AS SO_LUONG_VAN_DE,
    COUNT(DISTINCT dq.SOURCE_TABLE_ID) AS SO_BANG_ANH_HUONG,
    SUM(CASE WHEN dq.SEVERITY = 'CRITICAL' THEN 1 ELSE 0 END) AS SO_VAN_DE_NGHIEM_TRONG,
    SUM(CASE WHEN dq.SEVERITY = 'HIGH' THEN 1 ELSE 0 END) AS SO_VAN_DE_CAO,
    SUM(CASE WHEN dq.SEVERITY = 'MEDIUM' THEN 1 ELSE 0 END) AS SO_VAN_DE_TRUNG_BINH,
    SUM(CASE WHEN dq.SEVERITY = 'LOW' THEN 1 ELSE 0 END) AS SO_VAN_DE_THAP,
    AVG(ISNULL(dq.PERCENTAGE_AFFECTED, 0)) AS PHAN_TRAM_ANH_HUONG_TB,
    MIN(dq.PROCESS_DATE) AS NGAY_PHAT_HIEN_DAU_TIEN,
    MAX(dq.PROCESS_DATE) AS NGAY_PHAT_HIEN_GAN_DAY
FROM MODEL_REGISTRY.dbo.MODEL_DATA_QUALITY_LOG dq
WHERE dq.REMEDIATION_STATUS IN ('OPEN', 'IN_PROGRESS')
GROUP BY dq.ISSUE_TYPE
ORDER BY SO_LUONG_VAN_DE DESC;

-- 4. Tác động chất lượng dữ liệu đến các mô hình
SELECT 
    'TÁC ĐỘNG CHẤT LƯỢNG DỮ LIỆU ĐẾN CÁC MÔ HÌNH' AS SECTION_TITLE;

-- 4.1. Các mô hình bị ảnh hưởng bởi vấn đề chất lượng dữ liệu
WITH AffectedModels AS (
    SELECT 
        mr.MODEL_ID,
        mr.MODEL_NAME,
        mr.MODEL_VERSION,
        mt.TYPE_NAME,
        st.SOURCE_TABLE_ID,
        st.SOURCE_DATABASE + '.' + st.SOURCE_SCHEMA + '.' + st.SOURCE_TABLE_NAME AS TABLE_NAME,
        COUNT(DISTINCT dq.LOG_ID) AS ISSUE_COUNT,
        MAX(CASE dq.SEVERITY
                WHEN 'CRITICAL' THEN 4
                WHEN 'HIGH' THEN 3
                WHEN 'MEDIUM' THEN 2
                WHEN 'LOW' THEN 1
                ELSE 0
            END) AS MAX_SEVERITY_SCORE,
        MAX(CASE dq.SEVERITY
                WHEN 'CRITICAL' THEN 'CRITICAL'
                WHEN 'HIGH' THEN 'HIGH'
                WHEN 'MEDIUM' THEN 'MEDIUM'
                WHEN 'LOW' THEN 'LOW'
                ELSE 'UNKNOWN'
            END) AS MAX_SEVERITY
    FROM MODEL_REGISTRY.dbo.MODEL_REGISTRY mr
    JOIN MODEL_REGISTRY.dbo.MODEL_TYPE mt ON mr.TYPE_ID = mt.TYPE_ID
    JOIN MODEL_REGISTRY.dbo.MODEL_TABLE_USAGE tu ON mr.MODEL_ID = tu.MODEL_ID
    JOIN MODEL_REGISTRY.dbo.MODEL_SOURCE_TABLES st ON tu.SOURCE_TABLE_ID = st.SOURCE_TABLE_ID
    JOIN MODEL_REGISTRY.dbo.MODEL_DATA_QUALITY_LOG dq ON st.SOURCE_TABLE_ID = dq.SOURCE_TABLE_ID
    WHERE mr.IS_ACTIVE = 1
    AND GETDATE() BETWEEN mr.EFF_DATE AND mr.EXP_DATE
    AND tu.IS_ACTIVE = 1
    AND GETDATE() BETWEEN tu.EFF_DATE AND tu.EXP_DATE
    AND dq.REMEDIATION_STATUS IN ('OPEN', 'IN_PROGRESS')
    GROUP BY mr.MODEL_ID, mr.MODEL_NAME, mr.MODEL_VERSION, mt.TYPE_NAME, st.SOURCE_TABLE_ID, 
             st.SOURCE_DATABASE, st.SOURCE_SCHEMA, st.SOURCE_TABLE_NAME
)
SELECT
    MODEL_ID,
    MODEL_NAME AS TEN_MO_HINH,
    MODEL_VERSION AS PHIEN_BAN,
    TYPE_NAME AS LOAI_MO_HINH,
    COUNT(DISTINCT SOURCE_TABLE_ID) AS SO_BANG_CO_VAN_DE,
    SUM(ISSUE_COUNT) AS TONG_SO_VAN_DE,
    MAX(MAX_SEVERITY) AS MUC_DO_NGHIEM_TRONG_CAO_NHAT,
    STRING_AGG(TABLE_NAME, ', ') AS DANH_SACH_BANG_ANH_HUONG,
    CASE 
        WHEN MAX(MAX_SEVERITY_SCORE) >= 4 THEN 'Cao'
        WHEN MAX(MAX_SEVERITY_SCORE) >= 3 THEN 'Trung bình'
        ELSE 'Thấp'
    END AS MUC_DO_TAC_DONG
FROM AffectedModels
GROUP BY MODEL_ID, MODEL_NAME, MODEL_VERSION, TYPE_NAME
ORDER BY 
    MAX(MAX_SEVERITY_SCORE) DESC,
    SUM(ISSUE_COUNT) DESC;

-- 4.2. Chi tiết vấn đề chất lượng dữ liệu theo mô hình
WITH ModelIssues AS (
    SELECT 
        mr.MODEL_ID,
        mr.MODEL_NAME,
        mr.MODEL_VERSION,
        dq.LOG_ID,
        st.SOURCE_DATABASE + '.' + st.SOURCE_SCHEMA + '.' + st.SOURCE_TABLE_NAME AS TABLE_NAME,
        ISNULL(cd.COLUMN_NAME, 'N/A') AS COLUMN_NAME,
        dq.SEVERITY,
        dq.ISSUE_TYPE,
        dq.ISSUE_DESCRIPTION,
        dq.PROCESS_DATE,
        ROW_NUMBER() OVER (PARTITION BY mr.MODEL_ID ORDER BY 
            CASE dq.SEVERITY
                WHEN 'CRITICAL' THEN 1
                WHEN 'HIGH' THEN 2
                WHEN 'MEDIUM' THEN 3
                WHEN 'LOW' THEN 4
                ELSE 5
            END, 
            dq.PROCESS_DATE
        ) AS IssueRank
    FROM MODEL_REGISTRY.dbo.MODEL_REGISTRY mr
    JOIN MODEL_REGISTRY.dbo.MODEL_TABLE_USAGE tu ON mr.MODEL_ID = tu.MODEL_ID
    JOIN MODEL_REGISTRY.dbo.MODEL_SOURCE_TABLES st ON tu.SOURCE_TABLE_ID = st.SOURCE_TABLE_ID
    JOIN MODEL_REGISTRY.dbo.MODEL_DATA_QUALITY_LOG dq ON st.SOURCE_TABLE_ID = dq.SOURCE_TABLE_ID
    LEFT JOIN MODEL_REGISTRY.dbo.MODEL_COLUMN_DETAILS cd ON dq.COLUMN_ID = cd.COLUMN_ID
    WHERE mr.IS_ACTIVE = 1
    AND GETDATE() BETWEEN mr.EFF_DATE AND mr.EXP_DATE
    AND tu.IS_ACTIVE = 1
    AND GETDATE() BETWEEN tu.EFF_DATE AND tu.EXP_DATE
    AND dq.REMEDIATION_STATUS IN ('OPEN', 'IN_PROGRESS')
)
SELECT
    mi.MODEL_ID,
    mi.MODEL_NAME AS TEN_MO_HINH,
    mi.MODEL_VERSION AS PHIEN_BAN,
    mi.TABLE_NAME AS TEN_BANG,
    mi.COLUMN_NAME AS TEN_COT,
    mi.SEVERITY AS MUC_DO_NGHIEM_TRONG,
    mi.ISSUE_TYPE AS LOAI_VAN_DE,
    mi.ISSUE_DESCRIPTION AS MO_TA_VAN_DE,
    CONVERT(VARCHAR, mi.PROCESS_DATE, 103) AS NGAY_PHAT_HIEN
FROM ModelIssues mi
WHERE mi.IssueRank <= 10  -- Giới hạn 10 vấn đề nghiêm trọng nhất cho mỗi mô hình
ORDER BY mi.MODEL_NAME, mi.MODEL_VERSION, mi.IssueRank;

-- 5. Báo cáo tóm tắt đề xuất hành động
SELECT 
    'ĐỀ XUẤT HÀNH ĐỘNG CHO CHẤT LƯỢNG DỮ LIỆU' AS SECTION_TITLE;

-- 5.1. Các bảng cần ưu tiên cải thiện chất lượng
WITH PriorityTables AS (
    SELECT 
        st.SOURCE_TABLE_ID,
        st.SOURCE_DATABASE + '.' + st.SOURCE_SCHEMA + '.' + st.SOURCE_TABLE_NAME AS TABLE_NAME,
        st.DATA_QUALITY_SCORE,
        st.TABLE_TYPE,
        (
            SELECT COUNT(DISTINCT tu.MODEL_ID)
            FROM MODEL_REGISTRY.dbo.MODEL_TABLE_USAGE tu
            JOIN MODEL_REGISTRY.dbo.MODEL_REGISTRY mr ON tu.MODEL_ID = mr.MODEL_ID
            WHERE tu.SOURCE_TABLE_ID = st.SOURCE_TABLE_ID
            AND tu.IS_ACTIVE = 1
            AND mr.IS_ACTIVE = 1
            AND GETDATE() BETWEEN mr.EFF_DATE AND mr.EXP_DATE
        ) AS MODEL_COUNT,
        (
            SELECT COUNT(*)
            FROM MODEL_REGISTRY.dbo.MODEL_DATA_QUALITY_LOG dq
            WHERE dq.SOURCE_TABLE_ID = st.SOURCE_TABLE_ID
            AND dq.REMEDIATION_STATUS IN ('OPEN', 'IN_PROGRESS')
        ) AS ISSUE_COUNT,
        (
            SELECT COUNT(*)
            FROM MODEL_REGISTRY.dbo.MODEL_DATA_QUALITY_LOG dq
            WHERE dq.SOURCE_TABLE_ID = st.SOURCE_TABLE_ID
            AND dq.REMEDIATION_STATUS IN ('OPEN', 'IN_PROGRESS')
            AND dq.SEVERITY = 'CRITICAL'
        ) AS CRITICAL_ISSUE_COUNT
    FROM MODEL_REGISTRY.dbo.MODEL_SOURCE_TABLES st
    WHERE st.IS_ACTIVE = 1
)
SELECT
    SOURCE_TABLE_ID,
    TABLE_NAME AS TEN_BANG,
    DATA_QUALITY_SCORE AS DIEM_CHAT_LUONG,
    TABLE_TYPE AS LOAI_BANG,
    MODEL_COUNT AS SO_MO_HINH_SU_DUNG,
    ISSUE_COUNT AS SO_VAN_DE,
    CRITICAL_ISSUE_COUNT AS SO_VAN_DE_NGHIEM_TRONG,
    CASE 
        WHEN CRITICAL_ISSUE_COUNT > 0 THEN 'Cần xử lý ngay các vấn đề nghiêm trọng'
        WHEN ISSUE_COUNT > 5 THEN 'Cần rà soát và xử lý các vấn đề tồn đọng'
        WHEN DATA_QUALITY_SCORE < 5 THEN 'Cần cải thiện chất lượng dữ liệu tổng thể'
        ELSE 'Theo dõi và duy trì chất lượng'
    END AS DE_XUAT_HANH_DONG,
    CASE 
        WHEN CRITICAL_ISSUE_COUNT > 0 THEN 'Cao'
        WHEN ISSUE_COUNT > 5 OR DATA_QUALITY_SCORE < 5 THEN 'Trung bình'
        ELSE 'Thấp'
    END AS MUC_UU_TIEN
FROM PriorityTables
WHERE MODEL_COUNT > 0 -- Chỉ xem xét các bảng đang được sử dụng bởi ít nhất một mô hình
AND (CRITICAL_ISSUE_COUNT > 0 OR ISSUE_COUNT > 0 OR DATA_QUALITY_SCORE < 7)
ORDER BY 
    CASE 
        WHEN CRITICAL_ISSUE_COUNT > 0 THEN 1
        WHEN ISSUE_COUNT > 5 THEN 2
        WHEN DATA_QUALITY_SCORE < 5 THEN 3
        ELSE 4
    END,
    MODEL_COUNT DESC;

-- 5.2. Lịch làm mới dữ liệu cần thực hiện
WITH RefreshNeeds AS (
    SELECT 
        st.SOURCE_TABLE_ID,
        st.SOURCE_DATABASE + '.' + st.SOURCE_SCHEMA + '.' + st.SOURCE_TABLE_NAME AS TABLE_NAME,
        st.TABLE_TYPE,
        st.UPDATE_FREQUENCY,
        (
            SELECT MAX(PROCESS_DATE)
            FROM MODEL_REGISTRY.dbo.MODEL_SOURCE_REFRESH_LOG srl
            WHERE srl.SOURCE_TABLE_ID = st.SOURCE_TABLE_ID
            AND srl.REFRESH_STATUS = 'COMPLETED'
        ) AS LAST_REFRESH_DATE,
        DATEDIFF(DAY, 
            (SELECT MAX(PROCESS_DATE)
             FROM MODEL_REGISTRY.dbo.MODEL_SOURCE_REFRESH_LOG srl
             WHERE srl.SOURCE_TABLE_ID = st.SOURCE_TABLE_ID
             AND srl.REFRESH_STATUS = 'COMPLETED'), 
            GETDATE()) AS DAYS_SINCE_REFRESH,
        (
            SELECT COUNT(DISTINCT tu.MODEL_ID)
            FROM MODEL_REGISTRY.dbo.MODEL_TABLE_USAGE tu
            JOIN MODEL_REGISTRY.dbo.MODEL_REGISTRY mr ON tu.MODEL_ID = mr.MODEL_ID
            WHERE tu.SOURCE_TABLE_ID = st.SOURCE_TABLE_ID
            AND tu.IS_ACTIVE = 1
            AND mr.IS_ACTIVE = 1
            AND GETDATE() BETWEEN mr.EFF_DATE AND mr.EXP_DATE
        ) AS MODEL_COUNT
    FROM MODEL_REGISTRY.dbo.MODEL_SOURCE_TABLES st
    WHERE st.IS_ACTIVE = 1
)
SELECT
    SOURCE_TABLE_ID,
    TABLE_NAME AS TEN_BANG,
    TABLE_TYPE AS LOAI_BANG,
    UPDATE_FREQUENCY AS TAN_SUAT_CAP_NHAT,
    CONVERT(VARCHAR, LAST_REFRESH_DATE, 103) AS NGAY_CAP_NHAT_CUOI,
    DAYS_SINCE_REFRESH AS SO_NGAY_TU_CAP_NHAT_CUOI,
    MODEL_COUNT AS SO_MO_HINH_SU_DUNG,
    CASE 
        WHEN UPDATE_FREQUENCY = 'DAILY' AND DAYS_SINCE_REFRESH > 1 THEN 'Cập nhật ngay hôm nay'
        WHEN UPDATE_FREQUENCY = 'WEEKLY' AND DAYS_SINCE_REFRESH > 7 THEN 'Cập nhật trong tuần này'
        WHEN UPDATE_FREQUENCY = 'MONTHLY' AND DAYS_SINCE_REFRESH > 31 THEN 'Cập nhật trong tháng này'
        WHEN UPDATE_FREQUENCY = 'QUARTERLY' AND DAYS_SINCE_REFRESH > 92 THEN 'Cập nhật trong quý này'
        WHEN DAYS_SINCE_REFRESH > 60 THEN 'Kiểm tra tần suất cập nhật'
        ELSE 'Không cần cập nhật'
    END AS DE_XUAT_CAP_NHAT,
    CASE 
        WHEN (UPDATE_FREQUENCY = 'DAILY' AND DAYS_SINCE_REFRESH > 1) OR 
             (UPDATE_FREQUENCY = 'WEEKLY' AND DAYS_SINCE_REFRESH > 7 AND MODEL_COUNT > 5) THEN 'Cao'
        WHEN (UPDATE_FREQUENCY = 'WEEKLY' AND DAYS_SINCE_REFRESH > 7) OR 
             (UPDATE_FREQUENCY = 'MONTHLY' AND DAYS_SINCE_REFRESH > 31) OR
             (UPDATE_FREQUENCY = 'QUARTERLY' AND DAYS_SINCE_REFRESH > 92 AND MODEL_COUNT > 5) THEN 'Trung bình'
        ELSE 'Thấp'
    END AS MUC_UU_TIEN
FROM RefreshNeeds
WHERE MODEL_COUNT > 0
AND ((UPDATE_FREQUENCY = 'DAILY' AND DAYS_SINCE_REFRESH > 1) OR 
     (UPDATE_FREQUENCY = 'WEEKLY' AND DAYS_SINCE_REFRESH > 7) OR 
     (UPDATE_FREQUENCY = 'MONTHLY' AND DAYS_SINCE_REFRESH > 31) OR 
     (UPDATE_FREQUENCY = 'QUARTERLY' AND DAYS_SINCE_REFRESH > 92) OR
     DAYS_SINCE_REFRESH > 60)
ORDER BY 
    CASE MUC_UU_TIEN
        WHEN 'Cao' THEN 1
        WHEN 'Trung bình' THEN 2
        ELSE 3
    END,
    DAYS_SINCE_REFRESH DESC;