/*
Tên file: model_inventory_report.sql
Mô tả: Báo cáo danh mục mô hình trong hệ thống
Tác giả: Nguyễn Ngọc Bình
Ngày tạo: 2025-05-12
Phiên bản: 1.0

Báo cáo này cung cấp thông tin tổng quan về tất cả các mô hình trong hệ thống,
bao gồm trạng thái, thông tin về loại mô hình, hiệu suất và thông tin về nguồn dữ liệu.
*/

-- 1. Báo cáo tổng quan về danh mục mô hình
SELECT 
    'BÁO CÁO DANH MỤC MÔ HÌNH - ' + CONVERT(VARCHAR, GETDATE(), 103) AS REPORT_TITLE;

-- 1.1. Thống kê số lượng mô hình theo loại
SELECT 
    'THỐNG KÊ THEO LOẠI MÔ HÌNH' AS SECTION_TITLE;

SELECT 
    mt.TYPE_NAME AS LOAI_MO_HINH,
    COUNT(mr.MODEL_ID) AS TONG_SO_MO_HINH,
    SUM(CASE WHEN mr.IS_ACTIVE = 1 AND GETDATE() BETWEEN mr.EFF_DATE AND mr.EXP_DATE THEN 1 ELSE 0 END) AS DANG_HOAT_DONG,
    SUM(CASE WHEN mr.IS_ACTIVE = 1 AND GETDATE() < mr.EFF_DATE THEN 1 ELSE 0 END) AS SAP_HOAT_DONG,
    SUM(CASE WHEN mr.IS_ACTIVE = 1 AND GETDATE() > mr.EXP_DATE THEN 1 ELSE 0 END) AS DA_HET_HAN,
    SUM(CASE WHEN mr.IS_ACTIVE = 0 THEN 1 ELSE 0 END) AS KHONG_HOAT_DONG
FROM MODEL_REGISTRY.dbo.MODEL_REGISTRY mr
JOIN MODEL_REGISTRY.dbo.MODEL_TYPE mt ON mr.TYPE_ID = mt.TYPE_ID
GROUP BY mt.TYPE_NAME
ORDER BY TONG_SO_MO_HINH DESC;

-- 1.2. Thống kê số lượng mô hình theo phân khúc
SELECT 
    'THỐNG KÊ THEO PHÂN KHÚC' AS SECTION_TITLE;

SELECT 
    ISNULL(mr.MODEL_CATEGORY, 'Không phân loại') AS PHAN_KHUC,
    COUNT(mr.MODEL_ID) AS TONG_SO_MO_HINH,
    SUM(CASE WHEN mr.IS_ACTIVE = 1 AND GETDATE() BETWEEN mr.EFF_DATE AND mr.EXP_DATE THEN 1 ELSE 0 END) AS DANG_HOAT_DONG
FROM MODEL_REGISTRY.dbo.MODEL_REGISTRY mr
GROUP BY mr.MODEL_CATEGORY
ORDER BY TONG_SO_MO_HINH DESC;

-- 2. Danh sách chi tiết mô hình
SELECT 
    'DANH SÁCH MÔ HÌNH' AS SECTION_TITLE;

SELECT 
    mr.MODEL_ID,
    mr.MODEL_NAME AS TEN_MO_HINH,
    mr.MODEL_VERSION AS PHIEN_BAN,
    mt.TYPE_NAME AS LOAI_MO_HINH,
    mr.MODEL_CATEGORY AS PHAN_KHUC,
    CONVERT(VARCHAR, mr.EFF_DATE, 103) AS NGAY_BAT_DAU, 
    CONVERT(VARCHAR, mr.EXP_DATE, 103) AS NGAY_KET_THUC,
    CASE 
        WHEN mr.IS_ACTIVE = 0 THEN 'Không hoạt động'
        WHEN mr.IS_ACTIVE = 1 AND GETDATE() BETWEEN mr.EFF_DATE AND mr.EXP_DATE THEN 'Đang hoạt động'
        WHEN mr.IS_ACTIVE = 1 AND GETDATE() < mr.EFF_DATE THEN 'Sắp hoạt động'
        WHEN mr.IS_ACTIVE = 1 AND GETDATE() > mr.EXP_DATE THEN 'Đã hết hạn'
        ELSE 'Không xác định'
    END AS TRANG_THAI,
    (
        SELECT COUNT(DISTINCT tu.SOURCE_TABLE_ID)
        FROM MODEL_REGISTRY.dbo.MODEL_TABLE_USAGE tu
        WHERE tu.MODEL_ID = mr.MODEL_ID
    ) AS SO_BANG_DU_LIEU,
    (
        SELECT COUNT(*)
        FROM MODEL_REGISTRY.dbo.MODEL_PARAMETERS mp
        WHERE mp.MODEL_ID = mr.MODEL_ID
    ) AS SO_THAM_SO,
    (
        SELECT MAX(VALIDATION_DATE)
        FROM MODEL_REGISTRY.dbo.MODEL_VALIDATION_RESULTS mvr
        WHERE mvr.MODEL_ID = mr.MODEL_ID
    ) AS NGAY_DANH_GIA_GAN_NHAT,
    CONVERT(VARCHAR, mr.CREATED_DATE, 103) AS NGAY_TAO,
    mr.CREATED_BY AS NGUOI_TAO
FROM MODEL_REGISTRY.dbo.MODEL_REGISTRY mr
JOIN MODEL_REGISTRY.dbo.MODEL_TYPE mt ON mr.TYPE_ID = mt.TYPE_ID
ORDER BY 
    CASE 
        WHEN mr.IS_ACTIVE = 1 AND GETDATE() BETWEEN mr.EFF_DATE AND mr.EXP_DATE THEN 1
        WHEN mr.IS_ACTIVE = 1 AND GETDATE() < mr.EFF_DATE THEN 2
        WHEN mr.IS_ACTIVE = 1 AND GETDATE() > mr.EXP_DATE THEN 3
        ELSE 4
    END,
    mt.TYPE_NAME,
    mr.MODEL_NAME,
    mr.MODEL_VERSION DESC;

-- 3. Thông tin chi tiết về mô hình đang hoạt động
SELECT 
    'CHI TIẾT CÁC MÔ HÌNH ĐANG HOẠT ĐỘNG' AS SECTION_TITLE;

SELECT 
    mr.MODEL_ID,
    mr.MODEL_NAME AS TEN_MO_HINH,
    mr.MODEL_VERSION AS PHIEN_BAN,
    mt.TYPE_NAME AS LOAI_MO_HINH,
    mr.MODEL_CATEGORY AS PHAN_KHUC,
    mr.MODEL_DESCRIPTION AS MO_TA,
    CONVERT(VARCHAR, mr.EFF_DATE, 103) AS NGAY_BAT_DAU, 
    CONVERT(VARCHAR, mr.EXP_DATE, 103) AS NGAY_KET_THUC,
    DATEDIFF(DAY, GETDATE(), mr.EXP_DATE) AS NGAY_CON_LAI,
    mr.SOURCE_DATABASE + '.' + mr.SOURCE_SCHEMA + '.' + mr.SOURCE_TABLE_NAME AS BANG_KET_QUA,
    (
        SELECT COUNT(DISTINCT sm.SEGMENT_NAME)
        FROM MODEL_REGISTRY.dbo.MODEL_SEGMENT_MAPPING sm
        WHERE sm.MODEL_ID = mr.MODEL_ID AND sm.IS_ACTIVE = 1
    ) AS SO_PHAN_KHUC,
    (
        SELECT TOP 1 CASE
            WHEN mvr.VALIDATION_THRESHOLD_BREACHED = 1 THEN 'Cảnh báo'
            ELSE 'Bình thường'
        END
        FROM MODEL_REGISTRY.dbo.MODEL_VALIDATION_RESULTS mvr
        WHERE mvr.MODEL_ID = mr.MODEL_ID
        ORDER BY mvr.VALIDATION_DATE DESC
    ) AS TRANG_THAI_HIEU_SUAT,
    (
        SELECT COUNT(*)
        FROM MODEL_REGISTRY.dbo.MODEL_SOURCE_TABLES st
        JOIN MODEL_REGISTRY.dbo.MODEL_TABLE_USAGE tu ON st.SOURCE_TABLE_ID = tu.SOURCE_TABLE_ID
        WHERE tu.MODEL_ID = mr.MODEL_ID
        AND st.TABLE_TYPE = 'INPUT'
    ) AS SO_BANG_DAU_VAO,
    CONVERT(VARCHAR, mr.UPDATED_DATE, 103) AS NGAY_CAP_NHAT_CUOI,
    mr.UPDATED_BY AS NGUOI_CAP_NHAT
FROM MODEL_REGISTRY.dbo.MODEL_REGISTRY mr
JOIN MODEL_REGISTRY.dbo.MODEL_TYPE mt ON mr.TYPE_ID = mt.TYPE_ID
WHERE mr.IS_ACTIVE = 1 AND GETDATE() BETWEEN mr.EFF_DATE AND mr.EXP_DATE
ORDER BY mt.TYPE_NAME, mr.MODEL_NAME, mr.MODEL_VERSION DESC;

-- 4. Các mô hình sắp hết hạn (trong vòng 90 ngày tới)
SELECT 
    'CÁC MÔ HÌNH SẮP HẾT HẠN (trong vòng 90 ngày tới)' AS SECTION_TITLE;

SELECT 
    mr.MODEL_ID,
    mr.MODEL_NAME AS TEN_MO_HINH,
    mr.MODEL_VERSION AS PHIEN_BAN,
    mt.TYPE_NAME AS LOAI_MO_HINH,
    CONVERT(VARCHAR, mr.EXP_DATE, 103) AS NGAY_HET_HAN,
    DATEDIFF(DAY, GETDATE(), mr.EXP_DATE) AS NGAY_CON_LAI,
    (
        SELECT TOP 1 CASE
            WHEN mvr.VALIDATION_THRESHOLD_BREACHED = 1 THEN 'Cảnh báo'
            ELSE 'Bình thường'
        END
        FROM MODEL_REGISTRY.dbo.MODEL_VALIDATION_RESULTS mvr
        WHERE mvr.MODEL_ID = mr.MODEL_ID
        ORDER BY mvr.VALIDATION_DATE DESC
    ) AS TRANG_THAI_HIEU_SUAT
FROM MODEL_REGISTRY.dbo.MODEL_REGISTRY mr
JOIN MODEL_REGISTRY.dbo.MODEL_TYPE mt ON mr.TYPE_ID = mt.TYPE_ID
WHERE mr.IS_ACTIVE = 1 
AND GETDATE() BETWEEN mr.EFF_DATE AND mr.EXP_DATE
AND DATEDIFF(DAY, GETDATE(), mr.EXP_DATE) <= 90
ORDER BY NGAY_CON_LAI ASC;

-- 5. Các mô hình có vấn đề về hiệu suất
SELECT 
    'CÁC MÔ HÌNH CÓ VẤN ĐỀ VỀ HIỆU SUẤT' AS SECTION_TITLE;

SELECT 
    mr.MODEL_ID,
    mr.MODEL_NAME AS TEN_MO_HINH,
    mr.MODEL_VERSION AS PHIEN_BAN,
    mt.TYPE_NAME AS LOAI_MO_HINH,
    mr.MODEL_CATEGORY AS PHAN_KHUC,
    CONVERT(VARCHAR, mvr.VALIDATION_DATE, 103) AS NGAY_DANH_GIA,
    mvr.VALIDATION_TYPE AS LOAI_DANH_GIA,
    mvr.GINI,
    mvr.KS_STATISTIC AS KS,
    mvr.PSI,
    mvr.ACCURACY AS DO_CHINH_XAC,
    mvr.VALIDATION_COMMENTS AS NHAN_XET
FROM MODEL_REGISTRY.dbo.MODEL_REGISTRY mr
JOIN MODEL_REGISTRY.dbo.MODEL_TYPE mt ON mr.TYPE_ID = mt.TYPE_ID
JOIN MODEL_REGISTRY.dbo.MODEL_VALIDATION_RESULTS mvr ON mr.MODEL_ID = mvr.MODEL_ID
WHERE mr.IS_ACTIVE = 1 
AND GETDATE() BETWEEN mr.EFF_DATE AND mr.EXP_DATE
AND mvr.VALIDATION_THRESHOLD_BREACHED = 1
AND mvr.VALIDATION_DATE = (
    SELECT MAX(VALIDATION_DATE)
    FROM MODEL_REGISTRY.dbo.MODEL_VALIDATION_RESULTS
    WHERE MODEL_ID = mr.MODEL_ID
)
ORDER BY mvr.VALIDATION_DATE DESC;

-- 6. Thống kê số lượng bảng dữ liệu sử dụng theo loại
SELECT 
    'THỐNG KÊ SỐ LƯỢNG BẢNG DỮ LIỆU THEO LOẠI' AS SECTION_TITLE;

SELECT 
    st.TABLE_TYPE AS LOAI_BANG,
    COUNT(DISTINCT st.SOURCE_TABLE_ID) AS SO_LUONG_BANG,
    SUM(CASE WHEN DATEDIFF(DAY, MAX(srl.REFRESH_DATE), GETDATE()) <= 1 THEN 1 ELSE 0 END) AS UPDATED_LAST_DAY,
    SUM(CASE WHEN DATEDIFF(DAY, MAX(srl.REFRESH_DATE), GETDATE()) <= 7 THEN 1 ELSE 0 END) AS UPDATED_LAST_WEEK,
    SUM(CASE WHEN st.DATA_QUALITY_SCORE >= 8 THEN 1 ELSE 0 END) AS CHAT_LUONG_TOT
FROM MODEL_REGISTRY.dbo.MODEL_SOURCE_TABLES st
LEFT JOIN (
    SELECT 
        SOURCE_TABLE_ID,
        MAX(PROCESS_DATE) AS REFRESH_DATE
    FROM MODEL_REGISTRY.dbo.MODEL_SOURCE_REFRESH_LOG
    WHERE REFRESH_STATUS = 'COMPLETED'
    GROUP BY SOURCE_TABLE_ID
) srl ON st.SOURCE_TABLE_ID = srl.SOURCE_TABLE_ID
WHERE st.IS_ACTIVE = 1
GROUP BY st.TABLE_TYPE
ORDER BY SO_LUONG_BANG DESC;

-- 7. Thống kê mối quan hệ giữa mô hình và bảng dữ liệu
SELECT 
    'THỐNG KÊ MỐI QUAN HỆ MÔ HÌNH - BẢNG DỮ LIỆU' AS SECTION_TITLE;

SELECT 
    tu.USAGE_PURPOSE AS MUC_DICH_SU_DUNG,
    COUNT(DISTINCT tu.USAGE_ID) AS SO_LUONG_MOI_QUAN_HE,
    COUNT(DISTINCT tu.MODEL_ID) AS SO_LUONG_MO_HINH,
    COUNT(DISTINCT tu.SOURCE_TABLE_ID) AS SO_LUONG_BANG
FROM MODEL_REGISTRY.dbo.MODEL_TABLE_USAGE tu
JOIN MODEL_REGISTRY.dbo.MODEL_REGISTRY mr ON tu.MODEL_ID = mr.MODEL_ID
JOIN MODEL_REGISTRY.dbo.MODEL_SOURCE_TABLES st ON tu.SOURCE_TABLE_ID = st.SOURCE_TABLE_ID
WHERE tu.IS_ACTIVE = 1 AND mr.IS_ACTIVE = 1 AND st.IS_ACTIVE = 1
AND GETDATE() BETWEEN tu.EFF_DATE AND tu.EXP_DATE
GROUP BY tu.USAGE_PURPOSE
ORDER BY SO_LUONG_MOI_QUAN_HE DESC;

-- 8. Mô hình được cập nhật hoặc tạo mới gần đây (30 ngày)
SELECT 
    'MÔ HÌNH ĐƯỢC CẬP NHẬT HOẶC TẠO MỚI GẦN ĐÂY (30 ngày)' AS SECTION_TITLE;

SELECT 
    mr.MODEL_ID,
    mr.MODEL_NAME AS TEN_MO_HINH,
    mr.MODEL_VERSION AS PHIEN_BAN,
    mt.TYPE_NAME AS LOAI_MO_HINH,
    CASE 
        WHEN DATEDIFF(DAY, mr.CREATED_DATE, GETDATE()) <= 30 THEN 'Mô hình mới'
        ELSE 'Cập nhật'
    END AS LOAI_THAY_DOI,
    CONVERT(VARCHAR, CASE 
        WHEN DATEDIFF(DAY, mr.CREATED_DATE, GETDATE()) <= 30 THEN mr.CREATED_DATE
        ELSE mr.UPDATED_DATE
    END, 103) AS NGAY_THAY_DOI,
    CASE 
        WHEN DATEDIFF(DAY, mr.CREATED_DATE, GETDATE()) <= 30 THEN mr.CREATED_BY
        ELSE mr.UPDATED_BY
    END AS NGUOI_THAY_DOI
FROM MODEL_REGISTRY.dbo.MODEL_REGISTRY mr
JOIN MODEL_REGISTRY.dbo.MODEL_TYPE mt ON mr.TYPE_ID = mt.TYPE_ID
WHERE (DATEDIFF(DAY, mr.CREATED_DATE, GETDATE()) <= 30)
   OR (DATEDIFF(DAY, mr.UPDATED_DATE, GETDATE()) <= 30 AND mr.UPDATED_DATE IS NOT NULL)
ORDER BY NGAY_THAY_DOI DESC;

-- 9. Thống kê mô hình theo người tạo
SELECT 
    'THỐNG KÊ MÔ HÌNH THEO NGƯỜI TẠO' AS SECTION_TITLE;

SELECT 
    mr.CREATED_BY AS NGUOI_TAO,
    COUNT(mr.MODEL_ID) AS TONG_SO_MO_HINH,
    COUNT(DISTINCT mt.TYPE_ID) AS SO_LOAI_MO_HINH,
    MIN(mr.CREATED_DATE) AS NGAY_TAO_DAU_TIEN,
    MAX(mr.CREATED_DATE) AS NGAY_TAO_GAN_NHAT
FROM MODEL_REGISTRY.dbo.MODEL_REGISTRY mr
JOIN MODEL_REGISTRY.dbo.MODEL_TYPE mt ON mr.TYPE_ID = mt.TYPE_ID
GROUP BY mr.CREATED_BY
ORDER BY TONG_SO_MO_HINH DESC;