/*
Tên file: 05_model_table_usage_data.sql
Mô tả: Nhập dữ liệu mẫu cho bảng MODEL_TABLE_USAGE
Tác giả: Nguyễn Ngọc Bình
Ngày tạo: 2025-05-10
Phiên bản: 1.0
*/

-- Xóa dữ liệu cũ nếu cần
-- DELETE FROM MODEL_REGISTRY.dbo.MODEL_TABLE_USAGE;

-- Lấy các ID từ các bảng liên quan để tham chiếu
-- MODEL_IDs
DECLARE @PD_RETAIL_ID INT;
DECLARE @PD_MORTGAGE_ID INT;
DECLARE @PD_UNSECURED_ID INT;
DECLARE @PD_SME_ID INT;
DECLARE @BSCORE_RETAIL_ID INT;
DECLARE @ASCORE_RETAIL_ID INT;
DECLARE @ASCORE_RETAIL_BUREAU_ID INT;
DECLARE @EWS_RETAIL_ID INT;

SELECT @PD_RETAIL_ID = MODEL_ID FROM MODEL_REGISTRY.dbo.MODEL_REGISTRY WHERE MODEL_NAME = 'PD_RETAIL';
SELECT @PD_MORTGAGE_ID = MODEL_ID FROM MODEL_REGISTRY.dbo.MODEL_REGISTRY WHERE MODEL_NAME = 'PD_RETAIL_MORTGAGE';
SELECT @PD_UNSECURED_ID = MODEL_ID FROM MODEL_REGISTRY.dbo.MODEL_REGISTRY WHERE MODEL_NAME = 'PD_RETAIL_UNSECURED';
SELECT @PD_SME_ID = MODEL_ID FROM MODEL_REGISTRY.dbo.MODEL_REGISTRY WHERE MODEL_NAME = 'PD_SME';
SELECT @BSCORE_RETAIL_ID = MODEL_ID FROM MODEL_REGISTRY.dbo.MODEL_REGISTRY WHERE MODEL_NAME = 'BSCORE_RETAIL';
SELECT @ASCORE_RETAIL_ID = MODEL_ID FROM MODEL_REGISTRY.dbo.MODEL_REGISTRY WHERE MODEL_NAME = 'ASCORE_RETAIL';
SELECT @ASCORE_RETAIL_BUREAU_ID = MODEL_ID FROM MODEL_REGISTRY.dbo.MODEL_REGISTRY WHERE MODEL_NAME = 'ASCORE_RETAIL_BUREAU';
SELECT @EWS_RETAIL_ID = MODEL_ID FROM MODEL_REGISTRY.dbo.MODEL_REGISTRY WHERE MODEL_NAME = 'EWS_RETAIL';

-- TABLE_IDs
-- Common sources
DECLARE @DIM_CUSTOMER_ID INT;
DECLARE @DIM_ACCOUNT_ID INT;
DECLARE @FACT_ACCOUNT_BALANCE_ID INT;
DECLARE @FACT_TRANSACTION_ID INT;
DECLARE @FACT_PAYMENT_HISTORY_ID INT;
DECLARE @FACT_DELINQUENCY_ID INT;
DECLARE @FACT_CREDIT_BUREAU_ID INT;
DECLARE @DIM_PRODUCT_ID INT;
DECLARE @REF_RISK_GRADE_ID INT;
DECLARE @REF_MODEL_PARAMETERS_ID INT;

-- Model specific sources
DECLARE @PD_RETAIL_FEATURES_ID INT;
DECLARE @PD_SME_FEATURES_ID INT;
DECLARE @BSCORE_RETAIL_FEATURES_ID INT;
DECLARE @ASCORE_RETAIL_FEATURES_ID INT;
DECLARE @EWS_RETAIL_FEATURES_ID INT;

-- Model output tables
DECLARE @PD_RETAIL_RESULTS_ID INT;
DECLARE @PD_MORTGAGE_RESULTS_ID INT;
DECLARE @PD_UNSECURED_RESULTS_ID INT;
DECLARE @PD_SME_RESULTS_ID INT;
DECLARE @BSCORE_RETAIL_RESULTS_ID INT;
DECLARE @ASCORE_RETAIL_RESULTS_ID INT;
DECLARE @ASCORE_RETAIL_BUREAU_RESULTS_ID INT;
DECLARE @EWS_RETAIL_RESULTS_ID INT;

-- Common sources
SELECT @DIM_CUSTOMER_ID = SOURCE_TABLE_ID FROM MODEL_REGISTRY.dbo.MODEL_SOURCE_TABLES WHERE SOURCE_TABLE_NAME = 'DIM_CUSTOMER';
SELECT @DIM_ACCOUNT_ID = SOURCE_TABLE_ID FROM MODEL_REGISTRY.dbo.MODEL_SOURCE_TABLES WHERE SOURCE_TABLE_NAME = 'DIM_ACCOUNT';
SELECT @FACT_ACCOUNT_BALANCE_ID = SOURCE_TABLE_ID FROM MODEL_REGISTRY.dbo.MODEL_SOURCE_TABLES WHERE SOURCE_TABLE_NAME = 'FACT_ACCOUNT_BALANCE';
SELECT @FACT_TRANSACTION_ID = SOURCE_TABLE_ID FROM MODEL_REGISTRY.dbo.MODEL_SOURCE_TABLES WHERE SOURCE_TABLE_NAME = 'FACT_TRANSACTION';
SELECT @FACT_PAYMENT_HISTORY_ID = SOURCE_TABLE_ID FROM MODEL_REGISTRY.dbo.MODEL_SOURCE_TABLES WHERE SOURCE_TABLE_NAME = 'FACT_PAYMENT_HISTORY';
SELECT @FACT_DELINQUENCY_ID = SOURCE_TABLE_ID FROM MODEL_REGISTRY.dbo.MODEL_SOURCE_TABLES WHERE SOURCE_TABLE_NAME = 'FACT_DELINQUENCY';
SELECT @FACT_CREDIT_BUREAU_ID = SOURCE_TABLE_ID FROM MODEL_REGISTRY.dbo.MODEL_SOURCE_TABLES WHERE SOURCE_TABLE_NAME = 'FACT_CREDIT_BUREAU';
SELECT @DIM_PRODUCT_ID = SOURCE_TABLE_ID FROM MODEL_REGISTRY.dbo.MODEL_SOURCE_TABLES WHERE SOURCE_TABLE_NAME = 'DIM_PRODUCT';
SELECT @REF_RISK_GRADE_ID = SOURCE_TABLE_ID FROM MODEL_REGISTRY.dbo.MODEL_SOURCE_TABLES WHERE SOURCE_TABLE_NAME = 'REF_RISK_GRADE';
SELECT @REF_MODEL_PARAMETERS_ID = SOURCE_TABLE_ID FROM MODEL_REGISTRY.dbo.MODEL_SOURCE_TABLES WHERE SOURCE_TABLE_NAME = 'REF_MODEL_PARAMETERS';

-- Model specific sources
SELECT @PD_RETAIL_FEATURES_ID = SOURCE_TABLE_ID FROM MODEL_REGISTRY.dbo.MODEL_SOURCE_TABLES WHERE SOURCE_TABLE_NAME = 'PD_RETAIL_FEATURES';
SELECT @PD_SME_FEATURES_ID = SOURCE_TABLE_ID FROM MODEL_REGISTRY.dbo.MODEL_SOURCE_TABLES WHERE SOURCE_TABLE_NAME = 'PD_SME_FEATURES';
SELECT @BSCORE_RETAIL_FEATURES_ID = SOURCE_TABLE_ID FROM MODEL_REGISTRY.dbo.MODEL_SOURCE_TABLES WHERE SOURCE_TABLE_NAME = 'BSCORE_RETAIL_FEATURES';
SELECT @ASCORE_RETAIL_FEATURES_ID = SOURCE_TABLE_ID FROM MODEL_REGISTRY.dbo.MODEL_SOURCE_TABLES WHERE SOURCE_TABLE_NAME = 'ASCORE_RETAIL_FEATURES';
SELECT @EWS_RETAIL_FEATURES_ID = SOURCE_TABLE_ID FROM MODEL_REGISTRY.dbo.MODEL_SOURCE_TABLES WHERE SOURCE_TABLE_NAME = 'EWS_RETAIL_FEATURES';

-- Model output tables
SELECT @PD_RETAIL_RESULTS_ID = SOURCE_TABLE_ID FROM MODEL_REGISTRY.dbo.MODEL_SOURCE_TABLES WHERE SOURCE_TABLE_NAME = 'PD_RETAIL_RESULTS';
SELECT @PD_MORTGAGE_RESULTS_ID = SOURCE_TABLE_ID FROM MODEL_REGISTRY.dbo.MODEL_SOURCE_TABLES WHERE SOURCE_TABLE_NAME = 'PD_MORTGAGE_RESULTS';
SELECT @PD_UNSECURED_RESULTS_ID = SOURCE_TABLE_ID FROM MODEL_REGISTRY.dbo.MODEL_SOURCE_TABLES WHERE SOURCE_TABLE_NAME = 'PD_UNSECURED_RESULTS';
SELECT @PD_SME_RESULTS_ID = SOURCE_TABLE_ID FROM MODEL_REGISTRY.dbo.MODEL_SOURCE_TABLES WHERE SOURCE_TABLE_NAME = 'PD_SME_RESULTS';
SELECT @BSCORE_RETAIL_RESULTS_ID = SOURCE_TABLE_ID FROM MODEL_REGISTRY.dbo.MODEL_SOURCE_TABLES WHERE SOURCE_TABLE_NAME = 'BSCORE_RETAIL_RESULTS';
SELECT @ASCORE_RETAIL_RESULTS_ID = SOURCE_TABLE_ID FROM MODEL_REGISTRY.dbo.MODEL_SOURCE_TABLES WHERE SOURCE_TABLE_NAME = 'ASCORE_RETAIL_RESULTS';
SELECT @ASCORE_RETAIL_BUREAU_RESULTS_ID = SOURCE_TABLE_ID FROM MODEL_REGISTRY.dbo.MODEL_SOURCE_TABLES WHERE SOURCE_TABLE_NAME = 'ASCORE_RETAIL_BUREAU_RESULTS';
SELECT @EWS_RETAIL_RESULTS_ID = SOURCE_TABLE_ID FROM MODEL_REGISTRY.dbo.MODEL_SOURCE_TABLES WHERE SOURCE_TABLE_NAME = 'EWS_RETAIL_RESULTS';

-- Nhập dữ liệu vào bảng MODEL_TABLE_USAGE

-- PD RETAIL Model Table Usage
INSERT INTO MODEL_REGISTRY.dbo.MODEL_TABLE_USAGE (
    MODEL_ID,
    SOURCE_TABLE_ID,
    USAGE_PURPOSE,
    PRIORITY,
    USAGE_DESCRIPTION,
    EFF_DATE,
    EXP_DATE,
    IS_ACTIVE
)
VALUES
-- PD Retail input sources
(@PD_RETAIL_ID, @DIM_CUSTOMER_ID, 'Primary Input', 1, N'Thông tin khách hàng cá nhân', '2024-01-01', '2026-01-01', 1),
(@PD_RETAIL_ID, @DIM_ACCOUNT_ID, 'Primary Input', 1, N'Thông tin tài khoản và sản phẩm', '2024-01-01', '2026-01-01', 1),
(@PD_RETAIL_ID, @FACT_ACCOUNT_BALANCE_ID, 'Primary Input', 2, N'Dữ liệu số dư tài khoản hàng ngày', '2024-01-01', '2026-01-01', 1),
(@PD_RETAIL_ID, @FACT_TRANSACTION_ID, 'Primary Input', 2, N'Dữ liệu giao dịch', '2024-01-01', '2026-01-01', 1),
(@PD_RETAIL_ID, @FACT_PAYMENT_HISTORY_ID, 'Primary Input', 1, N'Lịch sử thanh toán', '2024-01-01', '2026-01-01', 1),
(@PD_RETAIL_ID, @FACT_DELINQUENCY_ID, 'Primary Input', 1, N'Thông tin nợ quá hạn', '2024-01-01', '2026-01-01', 1),
(@PD_RETAIL_ID, @PD_RETAIL_FEATURES_ID, 'Feature Source', 1, N'Bảng đặc trưng đã xử lý cho mô hình PD Retail', '2024-01-01', '2026-01-01', 1),
(@PD_RETAIL_ID, @DIM_PRODUCT_ID, 'Reference Data', 3, N'Thông tin sản phẩm', '2024-01-01', '2026-01-01', 1),
(@PD_RETAIL_ID, @REF_RISK_GRADE_ID, 'Reference Data', 3, N'Bảng tham chiếu cấp độ rủi ro', '2024-01-01', '2026-01-01', 1),
(@PD_RETAIL_ID, @REF_MODEL_PARAMETERS_ID, 'Parameter Source', 1, N'Tham số mô hình', '2024-01-01', '2026-01-01', 1),
(@PD_RETAIL_ID, @PD_RETAIL_RESULTS_ID, 'Result Storage', 1, N'Bảng lưu kết quả mô hình PD Retail', '2024-01-01', '2026-01-01', 1),

-- PD Mortgage input sources 
(@PD_MORTGAGE_ID, @DIM_CUSTOMER_ID, 'Primary Input', 1, N'Thông tin khách hàng cá nhân', '2024-03-01', '2026-03-01', 1),
(@PD_MORTGAGE_ID, @DIM_ACCOUNT_ID, 'Primary Input', 1, N'Thông tin tài khoản và sản phẩm', '2024-03-01', '2026-03-01', 1),
(@PD_MORTGAGE_ID, @FACT_ACCOUNT_BALANCE_ID, 'Primary Input', 2, N'Dữ liệu số dư tài khoản hàng ngày', '2024-03-01', '2026-03-01', 1),
(@PD_MORTGAGE_ID, @FACT_PAYMENT_HISTORY_ID, 'Primary Input', 1, N'Lịch sử thanh toán', '2024-03-01', '2026-03-01', 1),
(@PD_MORTGAGE_ID, @FACT_DELINQUENCY_ID, 'Primary Input', 1, N'Thông tin nợ quá hạn', '2024-03-01', '2026-03-01', 1),
(@PD_MORTGAGE_ID, @REF_RISK_GRADE_ID, 'Reference Data', 3, N'Bảng tham chiếu cấp độ rủi ro', '2024-03-01', '2026-03-01', 1),
(@PD_MORTGAGE_ID, @REF_MODEL_PARAMETERS_ID, 'Parameter Source', 1, N'Tham số mô hình', '2024-03-01', '2026-03-01', 1),
(@PD_MORTGAGE_ID, @PD_MORTGAGE_RESULTS_ID, 'Result Storage', 1, N'Bảng lưu kết quả mô hình PD Mortgage', '2024-03-01', '2026-03-01', 1),

-- BSCORE Retail input sources
(@BSCORE_RETAIL_ID, @DIM_CUSTOMER_ID, 'Primary Input', 1, N'Thông tin khách hàng cá nhân', '2024-02-01', '2026-02-01', 1),
(@BSCORE_RETAIL_ID, @DIM_ACCOUNT_ID, 'Primary Input', 1, N'Thông tin tài khoản và sản phẩm', '2024-02-01', '2026-02-01', 1),
(@BSCORE_RETAIL_ID, @FACT_ACCOUNT_BALANCE_ID, 'Primary Input', 2, N'Dữ liệu số dư tài khoản hàng ngày', '2024-02-01', '2026-02-01', 1),
(@BSCORE_RETAIL_ID, @FACT_TRANSACTION_ID, 'Primary Input', 2, N'Dữ liệu giao dịch', '2024-02-01', '2026-02-01', 1),
(@BSCORE_RETAIL_ID, @FACT_PAYMENT_HISTORY_ID, 'Primary Input', 1, N'Lịch sử thanh toán', '2024-02-01', '2026-02-01', 1),
(@BSCORE_RETAIL_ID, @FACT_DELINQUENCY_ID, 'Primary Input', 1, N'Thông tin nợ quá hạn', '2024-02-01', '2026-02-01', 1),
(@BSCORE_RETAIL_ID, @BSCORE_RETAIL_FEATURES_ID, 'Feature Source', 1, N'Bảng đặc trưng đã xử lý cho thẻ điểm hành vi', '2024-02-01', '2026-02-01', 1),
(@BSCORE_RETAIL_ID, @REF_RISK_GRADE_ID, 'Reference Data', 3, N'Bảng tham chiếu cấp độ rủi ro', '2024-02-01', '2026-02-01', 1),
(@BSCORE_RETAIL_ID, @REF_MODEL_PARAMETERS_ID, 'Parameter Source', 1, N'Tham số mô hình', '2024-02-01', '2026-02-01', 1),
(@BSCORE_RETAIL_ID, @BSCORE_RETAIL_RESULTS_ID, 'Result Storage', 1, N'Bảng lưu kết quả thẻ điểm hành vi', '2024-02-01', '2026-02-01', 1),

-- ASCORE Retail input sources
(@ASCORE_RETAIL_ID, @DIM_CUSTOMER_ID, 'Primary Input', 1, N'Thông tin khách hàng cá nhân', '2024-01-15', '2026-01-15', 1),
(@ASCORE_RETAIL_ID, @ASCORE_RETAIL_FEATURES_ID, 'Feature Source', 1, N'Bảng đặc trưng đã xử lý cho thẻ điểm đăng ký', '2024-01-15', '2026-01-15', 1),
(@ASCORE_RETAIL_ID, @DIM_PRODUCT_ID, 'Reference Data', 3, N'Thông tin sản phẩm', '2024-01-15', '2026-01-15', 1),
(@ASCORE_RETAIL_ID, @REF_RISK_GRADE_ID, 'Reference Data', 3, N'Bảng tham chiếu cấp độ rủi ro', '2024-01-15', '2026-01-15', 1),
(@ASCORE_RETAIL_ID, @REF_MODEL_PARAMETERS_ID, 'Parameter Source', 1, N'Tham số mô hình', '2024-01-15', '2026-01-15', 1),
(@ASCORE_RETAIL_ID, @ASCORE_RETAIL_RESULTS_ID, 'Result Storage', 1, N'Bảng lưu kết quả thẻ điểm đăng ký', '2024-01-15', '2026-01-15', 1),

-- ASCORE Retail with Bureau input sources
(@ASCORE_RETAIL_BUREAU_ID, @DIM_CUSTOMER_ID, 'Primary Input', 1, N'Thông tin khách hàng cá nhân', '2024-02-20', '2026-02-20', 1),
(@ASCORE_RETAIL_BUREAU_ID, @ASCORE_RETAIL_FEATURES_ID, 'Feature Source', 1, N'Bảng đặc trưng đã xử lý cho thẻ điểm đăng ký', '2024-02-20', '2026-02-20', 1),
(@ASCORE_RETAIL_BUREAU_ID, @FACT_CREDIT_BUREAU_ID, 'Primary Input', 1, N'Dữ liệu tín dụng từ cục thông tin tín dụng', '2024-02-20', '2026-02-20', 1),
(@ASCORE_RETAIL_BUREAU_ID, @DIM_PRODUCT_ID, 'Reference Data', 3, N'Thông tin sản phẩm', '2024-02-20', '2026-02-20', 1),
(@ASCORE_RETAIL_BUREAU_ID, @REF_RISK_GRADE_ID, 'Reference Data', 3, N'Bảng tham chiếu cấp độ rủi ro', '2024-02-20', '2026-02-20', 1),
(@ASCORE_RETAIL_BUREAU_ID, @REF_MODEL_PARAMETERS_ID, 'Parameter Source', 1, N'Tham số mô hình', '2024-02-20', '2026-02-20', 1),
(@ASCORE_RETAIL_BUREAU_ID, @ASCORE_RETAIL_BUREAU_RESULTS_ID, 'Result Storage', 1, N'Bảng lưu kết quả thẻ điểm đăng ký với dữ liệu tín dụng ngoài', '2024-02-20', '2026-02-20', 1),

-- EWS Retail input sources
(@EWS_RETAIL_ID, @DIM_CUSTOMER_ID, 'Primary Input', 1, N'Thông tin khách hàng cá nhân', '2024-03-01', '2026-03-01', 1),
(@EWS_RETAIL_ID, @DIM_ACCOUNT_ID, 'Primary Input', 1, N'Thông tin tài khoản và sản phẩm', '2024-03-01', '2026-03-01', 1),
(@EWS_RETAIL_ID, @FACT_ACCOUNT_BALANCE_ID, 'Primary Input', 1, N'Dữ liệu số dư tài khoản hàng ngày', '2024-03-01', '2026-03-01', 1),
(@EWS_RETAIL_ID, @FACT_TRANSACTION_ID, 'Primary Input', 1, N'Dữ liệu giao dịch', '2024-03-01', '2026-03-01', 1),
(@EWS_RETAIL_ID, @FACT_PAYMENT_HISTORY_ID, 'Primary Input', 1, N'Lịch sử thanh toán', '2024-03-01', '2026-03-01', 1),
(@EWS_RETAIL_ID, @FACT_DELINQUENCY_ID, 'Primary Input', 1, N'Thông tin nợ quá hạn', '2024-03-01', '2026-03-01', 1),
(@EWS_RETAIL_ID, @EWS_RETAIL_FEATURES_ID, 'Feature Source', 1, N'Bảng đặc trưng đã xử lý cho mô hình cảnh báo sớm', '2024-03-01', '2026-03-01', 1),
(@EWS_RETAIL_ID, @REF_MODEL_PARAMETERS_ID, 'Parameter Source', 1, N'Tham số mô hình', '2024-03-01', '2026-03-01', 1),
(@EWS_RETAIL_ID, @EWS_RETAIL_RESULTS_ID, 'Result Storage', 1, N'Bảng lưu kết quả mô hình cảnh báo sớm', '2024-03-01', '2026-03-01', 1),

-- PD SME input sources
(@PD_SME_ID, @DIM_CUSTOMER_ID, 'Primary Input', 1, N'Thông tin khách hàng doanh nghiệp', '2024-04-01', '2026-04-01', 1),
(@PD_SME_ID, @DIM_ACCOUNT_ID, 'Primary Input', 1, N'Thông tin tài khoản và sản phẩm', '2024-04-01', '2026-04-01', 1),
(@PD_SME_ID, @FACT_ACCOUNT_BALANCE_ID, 'Primary Input', 2, N'Dữ liệu số dư tài khoản hàng ngày', '2024-04-01', '2026-04-01', 1),
(@PD_SME_ID, @FACT_TRANSACTION_ID, 'Primary Input', 2, N'Dữ liệu giao dịch', '2024-04-01', '2026-04-01', 1),
(@PD_SME_ID, @FACT_PAYMENT_HISTORY_ID, 'Primary Input', 1, N'Lịch sử thanh toán', '2024-04-01', '2026-04-01', 1),
(@PD_SME_ID, @FACT_DELINQUENCY_ID, 'Primary Input', 1, N'Thông tin nợ quá hạn', '2024-04-01', '2026-04-01', 1),
(@PD_SME_ID, @PD_SME_FEATURES_ID, 'Feature Source', 1, N'Bảng đặc trưng đã xử lý cho mô hình PD SME', '2024-04-01', '2026-04-01', 1),
(@PD_SME_ID, @REF_RISK_GRADE_ID, 'Reference Data', 3, N'Bảng tham chiếu cấp độ rủi ro', '2024-04-01', '2026-04-01', 1),
(@PD_SME_ID, @REF_MODEL_PARAMETERS_ID, 'Parameter Source', 1, N'Tham số mô hình', '2024-04-01', '2026-04-01', 1),
(@PD_SME_ID, @PD_SME_RESULTS_ID, 'Result Storage', 1, N'Bảng lưu kết quả mô hình PD SME', '2024-04-01', '2026-04-01', 1);
GO

PRINT 'Đã nhập dữ liệu mẫu cho bảng MODEL_TABLE_USAGE thành công.';
GO