/*
Tên file: 01_vw_model_table_relationships.sql
Mô tả: Tạo view VW_MODEL_TABLE_RELATIONSHIPS để hiển thị tất cả các mối quan hệ giữa mô hình và bảng dữ liệu
Tác giả: Nguyễn Ngọc Bình
Ngày tạo: 2025-05-10
Phiên bản: 1.0
*/
USE MODEL_REGISTRY
GO

-- Kiểm tra nếu view đã tồn tại thì xóa
IF EXISTS (SELECT * FROM sys.views WHERE name = 'VW_MODEL_TABLE_RELATIONSHIPS' AND schema_id = SCHEMA_ID('dbo'))
    DROP VIEW dbo.VW_MODEL_TABLE_RELATIONSHIPS;
GO

-- Tạo view VW_MODEL_TABLE_RELATIONSHIPS
CREATE VIEW dbo.VW_MODEL_TABLE_RELATIONSHIPS AS
SELECT 
    mr.MODEL_ID,
    mr.MODEL_NAME,
    mr.MODEL_VERSION,
    mt.TYPE_CODE AS MODEL_TYPE_CODE,
    mt.TYPE_NAME AS MODEL_TYPE_NAME,
    mr.MODEL_CATEGORY,
    st.SOURCE_TABLE_ID,
    st.SOURCE_DATABASE,
    st.SOURCE_SCHEMA,
    st.SOURCE_TABLE_NAME,
    st.TABLE_TYPE,
    tu.USAGE_PURPOSE,
    tm.USAGE_TYPE,
    tm.IS_CRITICAL,
    tm.SEQUENCE_ORDER,
    tm.REQUIRED_COLUMNS,
    tm.FILTERS_APPLIED,
    tm.DATA_TRANSFORMATION,
    tu.PRIORITY,
    st.DATA_OWNER,
    st.UPDATE_FREQUENCY,
    st.DATA_LATENCY,
    mr.EFF_DATE AS MODEL_EFF_DATE,
    mr.EXP_DATE AS MODEL_EXP_DATE,
    tu.EFF_DATE AS USAGE_EFF_DATE,
    tu.EXP_DATE AS USAGE_EXP_DATE,
    CASE 
        WHEN mr.IS_ACTIVE = 0 THEN 'INACTIVE_MODEL'
        WHEN st.IS_ACTIVE = 0 THEN 'INACTIVE_TABLE'
        WHEN tu.IS_ACTIVE = 0 THEN 'INACTIVE_USAGE'
        WHEN GETDATE() BETWEEN mr.EFF_DATE AND mr.EXP_DATE 
             AND GETDATE() BETWEEN tu.EFF_DATE AND tu.EXP_DATE THEN 'ACTIVE'
        WHEN GETDATE() < mr.EFF_DATE OR GETDATE() < tu.EFF_DATE THEN 'PENDING'
        WHEN GETDATE() > mr.EXP_DATE OR GETDATE() > tu.EXP_DATE THEN 'EXPIRED'
        ELSE 'UNKNOWN'
    END AS RELATIONSHIP_STATUS,
    (
        SELECT MAX(PROCESS_DATE)
        FROM MODEL_REGISTRY.dbo.MODEL_SOURCE_REFRESH_LOG r
        WHERE r.SOURCE_TABLE_ID = st.SOURCE_TABLE_ID
        AND r.REFRESH_STATUS = 'COMPLETED'
    ) AS LAST_REFRESH_DATE,
    (
        SELECT COUNT(*)
        FROM MODEL_REGISTRY.dbo.MODEL_DATA_QUALITY_LOG dq
        WHERE dq.SOURCE_TABLE_ID = st.SOURCE_TABLE_ID
        AND dq.REMEDIATION_STATUS IN ('OPEN', 'IN_PROGRESS')
    ) AS OPEN_QUALITY_ISSUES,
    mr.CREATED_BY AS MODEL_CREATED_BY,
    mr.CREATED_DATE AS MODEL_CREATED_DATE,
    tu.CREATED_BY AS USAGE_CREATED_BY,
    tu.CREATED_DATE AS USAGE_CREATED_DATE
FROM MODEL_REGISTRY.dbo.MODEL_REGISTRY mr
JOIN MODEL_REGISTRY.dbo.MODEL_TYPE mt ON mr.TYPE_ID = mt.TYPE_ID
JOIN MODEL_REGISTRY.dbo.MODEL_TABLE_USAGE tu ON mr.MODEL_ID = tu.MODEL_ID
JOIN MODEL_REGISTRY.dbo.MODEL_SOURCE_TABLES st ON tu.SOURCE_TABLE_ID = st.SOURCE_TABLE_ID
LEFT JOIN MODEL_REGISTRY.dbo.MODEL_TABLE_MAPPING tm ON mr.MODEL_ID = tm.MODEL_ID AND st.SOURCE_TABLE_ID = tm.SOURCE_TABLE_ID;
GO

-- Thêm comment cho view
EXEC sys.sp_addextendedproperty @name = N'MS_Description', 
    @value = N'View hiển thị tất cả các mối quan hệ giữa mô hình và bảng dữ liệu', 
    @level0type = N'SCHEMA', @level0name = N'dbo', 
    @level1type = N'VIEW',  @level1name = N'VW_MODEL_TABLE_RELATIONSHIPS';
GO

PRINT N'View VW_MODEL_TABLE_RELATIONSHIPS đã được tạo thành công';
GO