/*
Tên file: uninstall.sql
Mô tả: Script ngắn gọn để gỡ bỏ hệ thống Đăng Ký Mô Hình
Ngày tạo: 2025-05-20
*/

SET NOCOUNT ON;
PRINT N'Bắt đầu gỡ bỏ hệ thống Model Registry...';

BEGIN TRY
    BEGIN TRANSACTION;

    -- Xóa Triggers
    PRINT N'Đang xóa Triggers...';
    DROP TRIGGER IF EXISTS dbo.TRG_UPDATE_MODEL_FEATURE_DEPENDENCIES;
    DROP TRIGGER IF EXISTS dbo.TRG_FEATURE_STAT_UPDATE;
    DROP TRIGGER IF EXISTS dbo.TRG_AUDIT_FEATURE_REGISTRY;
    DROP TRIGGER IF EXISTS dbo.TRG_UPDATE_MODEL_STATUS;
    DROP TRIGGER IF EXISTS dbo.TRG_VALIDATE_MODEL_SOURCES;
    DROP TRIGGER IF EXISTS dbo.TRG_AUDIT_MODEL_PARAMETERS;
    DROP TRIGGER IF EXISTS dbo.TRG_AUDIT_MODEL_REGISTRY;

    -- Xóa Views
    PRINT N'Đang xóa Views...';
    DROP VIEW IF EXISTS dbo.VW_FEATURE_LINEAGE;
    DROP VIEW IF EXISTS dbo.VW_FEATURE_DEPENDENCIES;
    DROP VIEW IF EXISTS dbo.VW_FEATURE_MODEL_USAGE;
    DROP VIEW IF EXISTS dbo.VW_FEATURE_CATALOG;
    DROP VIEW IF EXISTS dbo.VW_MODEL_LINEAGE;
    DROP VIEW IF EXISTS dbo.VW_DATA_QUALITY_SUMMARY;
    DROP VIEW IF EXISTS dbo.VW_MODEL_PERFORMANCE;
    DROP VIEW IF EXISTS dbo.VW_MODEL_TYPE_INFO;
    DROP VIEW IF EXISTS dbo.VW_MODEL_TABLE_RELATIONSHIPS;

    -- Xóa Functions
    PRINT N'Đang xóa Functions...';
    DROP FUNCTION IF EXISTS dbo.FN_VALIDATE_FEATURE;
    DROP FUNCTION IF EXISTS dbo.FN_GET_FEATURE_HISTORY;
    DROP FUNCTION IF EXISTS dbo.FN_CALCULATE_FEATURE_DRIFT;
    DROP FUNCTION IF EXISTS dbo.FN_GET_MODEL_VERSION_INFO;
    DROP FUNCTION IF EXISTS dbo.FN_CALCULATE_KS;
    DROP FUNCTION IF EXISTS dbo.FN_CALCULATE_PSI;
    DROP FUNCTION IF EXISTS dbo.FN_GET_MODEL_SCORE;

    -- Xóa Tables (theo thứ tự dependency)
    PRINT N'Đang xóa Tables...';
    DROP TABLE IF EXISTS dbo.FEATURE_REFRESH_LOG;
    DROP TABLE IF EXISTS dbo.FEATURE_MODEL_MAPPING;
    DROP TABLE IF EXISTS dbo.FEATURE_DEPENDENCIES;
    DROP TABLE IF EXISTS dbo.FEATURE_STATS;
    DROP TABLE IF EXISTS dbo.FEATURE_VALUES;
    DROP TABLE IF EXISTS dbo.FEATURE_SOURCE_TABLES;
    DROP TABLE IF EXISTS dbo.FEATURE_TRANSFORMATIONS;
    DROP TABLE IF EXISTS dbo.FEATURE_REGISTRY;
    DROP TABLE IF EXISTS dbo.MODEL_DATA_QUALITY_LOG;
    DROP TABLE IF EXISTS dbo.MODEL_SOURCE_REFRESH_LOG;
    DROP TABLE IF EXISTS dbo.MODEL_VALIDATION_RESULTS;
    DROP TABLE IF EXISTS dbo.MODEL_SEGMENT_MAPPING;
    DROP TABLE IF EXISTS dbo.MODEL_TABLE_MAPPING;
    DROP TABLE IF EXISTS dbo.MODEL_TABLE_USAGE;
    DROP TABLE IF EXISTS dbo.MODEL_COLUMN_DETAILS;
    DROP TABLE IF EXISTS dbo.MODEL_SOURCE_TABLES;
    DROP TABLE IF EXISTS dbo.MODEL_PARAMETERS;
    DROP TABLE IF EXISTS dbo.MODEL_REGISTRY;
    DROP TABLE IF EXISTS dbo.MODEL_TYPE;

    COMMIT TRANSACTION;
    PRINT N'Gỡ bỏ hoàn tất! Tất cả thành phần đã được xóa.';

END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
    PRINT N'Lỗi: ' + ERROR_MESSAGE();
END CATCH;